<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:module-using-errormapping="http://www.mulesoft.org/schema/mule/module-using-errormapping"
      xmlns="http://www.mulesoft.org/schema/mule/core"
      xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/module-using-errormapping http://www.mulesoft.org/schema/mule/module-using-errormapping/current/mule-module-using-errormapping.xsd">

    <module-using-errormapping:config name="petstoreconfig" username="john"/>

    <configuration defaultErrorHandler-ref="catchAllSMART_CONNECTOR_CUSTOM_ERROR_TIMEOUT"/>

    <error-handler name="catchAllSMART_CONNECTOR_CUSTOM_ERROR_TIMEOUT">
        <on-error-continue type="MODULE-USING-ERRORMAPPING:SMART_CONNECTOR_CUSTOM_ERROR_TIMEOUT">
            <!-- using a normal MP within the on-error-continue chain scenario -->
            <set-payload value="Timeout happened!"/>
        </on-error-continue>
        <on-error-continue type="MODULE-USING-ERRORMAPPING:SMART_CONNECTOR_CUSTOM_ERROR_SECURITY">
            <!-- using a xml operation within the on-error-continue chain scenario -->
            <module-using-errormapping:simple-op config-ref="petstoreconfig" />
        </on-error-continue>
    </error-handler>

    <flow name="noMapping">
        <module-using-errormapping:fail-raise-error config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]"/>
        <error-handler>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="multipleMappingsDirectlyFromSmartConnector">
        <module-using-errormapping:fail-raise-error config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]"/>
        <error-handler>
            <on-error-continue type="MODULE-USING-ERRORMAPPING:SMART_CONNECTOR_CUSTOM_ERROR_CONNECTIVITY">
                <set-payload value="Could not connect."/>
            </on-error-continue>
            <on-error-continue type="MODULE-USING-ERRORMAPPING:SMART_CONNECTOR_CUSTOM_ERROR_EXPRESSION">
                <set-payload value="Bad expression."/>
            </on-error-continue>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="simpleMapping">
        <module-using-errormapping:fail-raise-error config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]">
            <error-mapping targetType="APP:MY_REQUESTER"/>
        </module-using-errormapping:fail-raise-error>
        <error-handler>
            <on-error-continue type="APP:MY_REQUESTER">
                <set-payload value="Could not connect."/>
            </on-error-continue>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="complexMapping">
        <module-using-errormapping:fail-raise-error config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]">
            <error-mapping sourceType="MODULE-USING-ERRORMAPPING:SMART_CONNECTOR_CUSTOM_ERROR_CONNECTIVITY" targetType="APP:MY_REQUESTER"/>
        </module-using-errormapping:fail-raise-error>
        <error-handler>
            <on-error-continue type="APP:MY_REQUESTER">
                <set-payload value="Could not connect."/>
            </on-error-continue>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="multipleMappings">
        <module-using-errormapping:fail-raise-error config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]">
            <error-mapping sourceType="MODULE-USING-ERRORMAPPING:SMART_CONNECTOR_CUSTOM_ERROR_CONNECTIVITY" targetType="APP:MY_REQUESTER"/>
            <error-mapping sourceType="MODULE-USING-ERRORMAPPING:SMART_CONNECTOR_CUSTOM_ERROR_EXPRESSION" targetType="APP:MY_OTHER_ERROR"/>
        </module-using-errormapping:fail-raise-error>
        <error-handler>
            <on-error-continue type="APP:MY_REQUESTER">
                <set-payload value="Could not connect."/>
            </on-error-continue>
            <on-error-continue type="APP:MY_OTHER_ERROR">
                <set-payload value="Bad expression."/>
            </on-error-continue>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="simpleMappingProxy">
        <module-using-errormapping:fail-proxy config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]"
                                              errorMappingTargetType="APP:MY_REQUESTER"/>
        <error-handler>
            <on-error-continue type="APP:MY_REQUESTER">
                <set-payload value="Could not connect."/>
            </on-error-continue>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="complexMappingProxy">
        <module-using-errormapping:fail-proxy config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]"
                                              errorMappingTargetType="APP:MY_REQUESTER" errorMappingSourceType="CONNECTIVITY"/>
        <error-handler>
            <on-error-continue type="APP:MY_REQUESTER">
                <set-payload value="Could not connect."/>
            </on-error-continue>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="multipleMappingsProxy">
        <module-using-errormapping:fail-proxy config-ref="petstoreconfig" petNames="#[vars.names]" failExpression="#[vars.failExpression]"
                                              errorMappingTargetType="APP:MY_REQUESTER" errorMappingSourceType="CONNECTIVITY"
                                              secondErrorMappingTargetType="APP:MY_OTHER_ERROR" secondErrorMappingSourceType="EXPRESSION"/>
        <error-handler>
            <on-error-continue type="APP:MY_REQUESTER">
                <set-payload value="Could not connect."/>
            </on-error-continue>
            <on-error-continue type="APP:MY_OTHER_ERROR">
                <set-payload value="Bad expression."/>
            </on-error-continue>
            <on-error-continue>
                <set-payload value="Error."/>
            </on-error-continue>
        </error-handler>
    </flow>

    <flow name="globalMappingWithDefaultErrorHandlerTimeout">
        <module-using-errormapping:fail-by-timeout config-ref="petstoreconfig" petNames="#[vars.names]"/>
    </flow>

    <flow name="globalMappingWithDefaultErrorHandlerSecurity">
        <module-using-errormapping:fail-by-security config-ref="petstoreconfig" petNames="#[vars.names]"/>
    </flow>

    <flow name="globalMappingWithDefaultErrorHandlerTimeoutThruSubflow">
        <flow-ref name="aSubFlow" />
    </flow>

    <sub-flow name="aSubFlow">
        <module-using-errormapping:fail-by-timeout config-ref="petstoreconfig" petNames="#[vars.names]"/>
    </sub-flow>

    <flow name="globalMappingWithDefaultErrorHandlerTimeoutThruSubSubflow">
        <flow-ref name="aSubSubFlow" />
    </flow>

    <sub-flow name="aSubSubFlow">
        <flow-ref name="aSubFlow" />
    </sub-flow>
</mule>
